# Generated by Django 6.0.6 on 2026-07-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_teacher', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=40)),
            ],
        ),
    ]
