# Generated by Django 6.0.6 on 2026-07-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
