# Generated by Django 6.0.6 on 2026-07-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_schoolclass_class_teacher'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass'),
        ),
    ]
