# Generated by Django 6.0.6 on 2026-07-10 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_alter_schoolclass_class_teacher'),
        ('students', '0002_remove_student_class_name_student_school_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('ICT', 'ICT'), ('RME', 'RME'), ('French', 'French'), ('Creative Arts', 'Creative Arts')], max_length=50)),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('score', models.PositiveIntegerField()),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('remarks', models.CharField(blank=True, max_length=30)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
