# Generated by Django 6.0.6 on 2026-07-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='subject',
            field=models.CharField(choices=[('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Creative Art', 'Creative Art'), ('RME', 'RME'), ('OWOP', 'OWOP'), ('History', 'History'), ('French', 'French'), ('Pre-Tech', 'Pre-Tech'), ('Home Economics', 'Home Economics'), ('Fante', 'Fante'), ('ICT', 'ICT')], max_length=50),
        ),
    ]
